<div class="not-slide">

[![Abrir no Google Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/professorviniciusramos/EGC5310-EstruturasDados/blob/main/Semana02/EGC5310-EstruturasDados-S02-99-Aula-Mestre.ipynb)

</div>

## EGC5310 {.title-slide-custom}

<img src="../assets/Logo_03.png" class="course-logo" alt="Logo Ciência de Dados UFSC">

<div class="course-name">ESTRUTURAS DE DADOS</div>
<div class="week-label">SEMANA 02</div>
<div class="subtitle-custom">Representação de dados e caracterização de problemas computacionais</div>

## Como decidimos a forma de <span class="gold">representar</span><br>um problema no computador? {.question-slide}

## Na semana passada...

```python
estudantes = [
    {"matricula": 1023, "nome": "Ana", "curso": "Ciência de Dados"},
    {"matricula": 1047, "nome": "Bruno", "curso": "Ciência de Dados"},
    {"matricula": 1082, "nome": "Carla", "curso": "Engenharia"},
]
```

::: {.fragment .prompt-gold}
**O que fizemos para encontrar a matrícula 1082?**
:::

## Uma decisão que não investigamos

<div class="prompt-gold"><code>{"matricula": 1082, "nome": "Carla", "curso": "Engenharia"}</code></div>

<div class="question-list">
  <div class="fragment"><strong>Por que</strong> os dados estavam representados assim?</div>
  <div class="fragment gold-text">Essa era a única possibilidade?</div>
</div>

## O computador não conhece “estudante”

:::: {.columns}
::: {.column width="46%"}
### Mundo do problema
**Estudante**
- matrícula: `1082`
- nome: `Carla`
- curso: `Engenharia`
:::
::: {.column width="8%"}
<div class="fragment" style="font-size:2.5em; text-align:center; margin-top:1.2em;">→</div>
:::
::: {.column width="46%"}
### Programa
<div class="fragment question-big">?</div>
:::
::::

::: {.fragment .prompt-gold}
Como transformamos aquilo que existe no problema em algo que o programa consegue manipular?
:::

## Uma possibilidade

```python
estudante = [1082, "Carla", "Engenharia"]
estudante[2]
```

::: {.fragment .question-big}
O que significa o **2**?
:::

::: {.fragment .small-note}
A representação funciona. Mas parte do significado está fora dela.
:::

## Outra possibilidade

```python
estudante = {
    "matricula": 1082,
    "nome": "Carla",
    "curso": "Engenharia"
}

estudante["curso"]
```

<div class="question-list">
  <div class="fragment">Guardamos informações diferentes?</div>
  <div class="fragment">Representamos da mesma maneira?</div>
  <div class="fragment gold-text">Qual é melhor?</div>
</div>

## Antes de escolher, precisamos conhecer possibilidades

<div class="three-words">
  <span class="fragment">Representar.</span>
  <span class="fragment blue">Organizar.</span>
  <span class="fragment gold">Manipular.</span>
</div>

::: {.fragment .small-note}
Não precisamos dominar todas as estruturas agora. Vamos construir um pequeno repertório.
:::

## Um pequeno álbum de figurinhas

Queremos representar coisas diferentes:

<div class="question-list">
  <div class="fragment">uma <strong>figurinha</strong>;</div>
  <div class="fragment">as figurinhas que <strong>temos</strong>;</div>
  <div class="fragment">as <strong>repetidas</strong>;</div>
  <div class="fragment"><strong>quantidades</strong>;</div>
  <div class="fragment">informações estruturadas sobre cada figurinha.</div>
</div>

::: {.fragment .prompt-gold}
Tudo isso precisa ser representado da mesma maneira?
:::

## Uma figurinha como lista

```python
figurinha = [37, "Goleiro", "Brasil", False]
print(figurinha[1])
```

::: {.fragment .question-big}
O que significa a posição **1**?
:::

In [1]:
figurinha_lista = [37, "Goleiro", "Brasil", False]
print(figurinha_lista[1])

Goleiro


## E uma tupla?

```python
figurinha = (37, "Goleiro", "Brasil", False)
print(figurinha[1])
```

::: {.fragment .small-note}
Outra forma de agrupar valores em posições. Não precisamos aprofundar lista × tupla agora.
:::

In [2]:
figurinha_tupla = (37, "Goleiro", "Brasil", False)
print(figurinha_tupla[1])

Goleiro


## E se os nomes fizerem parte da representação?

```python
figurinha = {
    "numero": 37,
    "jogador": "Goleiro",
    "selecao": "Brasil",
    "repetida": False
}
```

```python
figurinha["jogador"]
```

::: {.fragment .prompt-gold}
O que ficou **explícito**?
:::

In [3]:
figurinha_dict = {"numero":37,"jogador":"Goleiro","selecao":"Brasil","repetida":False}
print(figurinha_dict["jogador"])

Goleiro


## Agora o problema mudou

### Quais figurinhas eu tenho?

```python
tenho = {1, 2, 5, 8, 13}
repetidas = {8, 13, 21}

5 in tenho
```

::: {.fragment .question-big}
Estamos representando uma figurinha ou **outra coisa**?
:::

In [4]:
tenho = {1, 2, 5, 8, 13}
repetidas = {8, 13, 21}
amigo_precisa = {5, 8, 21, 30}
print("Tenho a figurinha 5?", 5 in tenho)
print("Posso trocar com meu amigo:", repetidas & amigo_precisa)

Tenho a figurinha 5? True
Posso trocar com meu amigo: {8, 21}


## E se os dados forem quantidades?

```python
import numpy as np
quantidades = np.array([1, 0, 2, 1, 3])
```

<div class="fragment small-note">Agora temos uma coleção homogênea: quantidades de figurinhas.</div>

::: {.fragment .prompt-gold}
A estrutura aparece porque **mudou aquilo que queremos representar**.
:::

In [5]:
import numpy as np
quantidades=np.array([1,0,2,1,3])
print("Quantidade da terceira figurinha:", quantidades[2])

Quantidade da terceira figurinha: 2


## Podemos criar nossa própria representação

```python
class Figurinha:
    def __init__(self, numero, jogador, selecao):
        self.numero = numero
        self.jogador = jogador
        self.selecao = selecao
```

::: {.fragment .prompt-gold}
**Você não precisa saber programar isso agora.**
:::

<div class="fragment small-note">Podemos construir uma representação própria para um conceito do problema.</div>

In [6]:
class Figurinha:
    def __init__(self, numero, jogador, selecao):
        self.numero=numero; self.jogador=jogador; self.selecao=selecao
figurinha_obj=Figurinha(37,"Goleiro","Brasil")
print(figurinha_obj.jogador)

Goleiro


## Várias possibilidades

<div class="three-words"><span>Lista</span><span class="blue">Tupla</span><span class="gold">Dicionário</span></div>
<div class="three-words" style="margin-top:0.8em;"><span>Conjunto</span><span class="blue">Array</span><span class="gold">Objeto</span></div>

::: {.fragment .question-big}
Por que não usamos uma única representação para tudo no álbum?
:::

::: {.fragment .small-note}
Não são seis respostas equivalentes para a mesma pergunta.
:::

## Voltamos ao Sistema Acadêmico

Precisamos representar um estudante com:
- matrícula;
- nome;
- curso;
- semestre de ingresso;
- situação acadêmica.

::: {.fragment .question-big}
Como você representaria esse estudante?
:::

## AGORA É COM VOCÊ {.question-slide}

::: {.prompt-gold}
### Notebook Estudante — Atividade 1
Represente o mesmo estudante de **duas maneiras diferentes**.

**Você pode copiar e adaptar as ideias do álbum.**
:::

<div class="small-note">Quem conhece outra possibilidade também pode utilizá-la — desde que consiga justificá-la.</div>

## Enquanto você trabalha...

Para cada representação:
1. Como obter o **curso**?
2. O significado dos campos fica explícito?
3. Como acrescentar `email`?
4. Qual vantagem você percebe?
5. Qual limitação você percebe?

::: {.prompt-gold}
**Qual das duas você escolheria neste momento? Por quê?**
:::

## Duas representações podem funcionar

:::: {.columns}
::: {.column width="48%"}
```python
estudante = [1082, "Carla", "Engenharia", 2026, "ativo"]
```
:::
::: {.column width="48%"}
```python
estudante = {
    "matricula": 1082,
    "nome": "Carla",
    "curso": "Engenharia",
    "ingresso": 2026,
    "situacao": "ativo"
}
```
:::
::::

::: {.fragment .question-big}
Se as duas funcionam, como escolhemos?
:::

## O problema cresceu

<div class="student-row"><div class="student-card"><div class="mat">1082</div><div class="name">Carla</div><div class="course">Engenharia</div></div></div>
<div class="fragment" style="text-align:center; font-size:2em;">↓</div>
<div class="fragment prompt-gold"><strong>Disciplinas cursadas</strong>: código · semestre · nota · situação</div>

<div class="question-list">
  <div class="fragment">Onde colocamos essas informações?</div>
  <div class="fragment">Uma disciplina é apenas mais um atributo?</div>
  <div class="fragment gold-text">A nota pertence à disciplina ou à relação estudante–disciplina?</div>
</div>

## Antes de escolher, pergunte o que precisamos fazer

<div class="question-list">
  <div class="fragment">localizar estudante pela matrícula;</div>
  <div class="fragment">obter o curso;</div>
  <div class="fragment">listar estudantes de um curso;</div>
  <div class="fragment">listar disciplinas cursadas;</div>
  <div class="fragment">inserir estudante;</div>
  <div class="fragment">atualizar informação.</div>
</div>

::: {.fragment .prompt-gold}
A mesma representação facilita todas essas operações?
:::

## Uma primeira regra {.concept-slide}

<div class="concept-definition">**DADOS + OPERAÇÕES → REQUISITOS DA REPRESENTAÇÃO**</div>

<div class="fragment small-note">Não começamos pela estrutura que conhecemos. Começamos pelo problema que precisamos resolver.</div>

## Agora vamos sair das ideias e olhar o código

<div class="prompt-gold">A operação é simples: <strong>encontrar a matrícula 1082</strong>.</div>

```python
estudantes_lista = [
    {"matricula": 1023, "nome": "Ana", "curso": "CD"},
    {"matricula": 1047, "nome": "Bruno", "curso": "CD"},
    {"matricula": 1082, "nome": "Carla", "curso": "Engenharia"},
    {"matricula": 1125, "nome": "Daniel", "curso": "CD"},
]
```

In [7]:
estudantes_lista = [
    {"matricula":1023,"nome":"Ana","curso":"CD"},
    {"matricula":1047,"nome":"Bruno","curso":"CD"},
    {"matricula":1082,"nome":"Carla","curso":"Engenharia"},
    {"matricula":1125,"nome":"Daniel","curso":"CD"},
]
estudantes_lista

[{'matricula': 1023, 'nome': 'Ana', 'curso': 'CD'},
 {'matricula': 1047, 'nome': 'Bruno', 'curso': 'CD'},
 {'matricula': 1082, 'nome': 'Carla', 'curso': 'Engenharia'},
 {'matricula': 1125, 'nome': 'Daniel', 'curso': 'CD'}]

## Busca na lista

```python
def buscar_matricula(estudantes, matricula):
    for estudante in estudantes:
        if estudante["matricula"] == matricula:
            return estudante
    return None
```

::: {.fragment .question-big}
O que o código efetivamente faz para encontrar 1082?
:::

In [8]:
def buscar_matricula(estudantes, matricula):
    for estudante in estudantes:
        if estudante["matricula"] == matricula:
            return estudante
    return None
buscar_matricula(estudantes_lista,1082)

{'matricula': 1082, 'nome': 'Carla', 'curso': 'Engenharia'}

## Vamos tornar o trabalho visível

```python
def buscar_matricula_contando(estudantes, matricula):
    comparacoes = 0
    for estudante in estudantes:
        comparacoes += 1
        if estudante["matricula"] == matricula:
            return estudante, comparacoes
    return None, comparacoes
```

::: {.fragment .prompt-gold}
A operação é a mesma. O trabalho foi sempre o mesmo?
:::

In [9]:
def buscar_matricula_contando(estudantes, matricula):
    comparacoes=0
    for estudante in estudantes:
        comparacoes += 1
        if estudante["matricula"] == matricula:
            return estudante, comparacoes
    return None, comparacoes
for alvo in [1023,1082,1125,9999]:
    resultado, comparacoes = buscar_matricula_contando(estudantes_lista, alvo)
    print(f"matrícula={alvo} | comparações={comparacoes} | encontrado={resultado is not None}")

matrícula=1023 | comparações=1 | encontrado=True
matrícula=1082 | comparações=3 | encontrado=True
matrícula=1125 | comparações=4 | encontrado=True
matrícula=9999 | comparações=4 | encontrado=False


## Mudamos a representação

```python
estudantes_dict = {
    1023: {"nome": "Ana", "curso": "CD"},
    1047: {"nome": "Bruno", "curso": "CD"},
    1082: {"nome": "Carla", "curso": "Engenharia"},
    1125: {"nome": "Daniel", "curso": "CD"},
}

estudantes_dict.get(1082)
```

::: {.fragment .question-big}
O que desapareceu do nosso código?
:::

In [10]:
estudantes_dict={
1023:{"nome":"Ana","curso":"CD"},1047:{"nome":"Bruno","curso":"CD"},
1082:{"nome":"Carla","curso":"Engenharia"},1125:{"nome":"Daniel","curso":"CD"}}
estudantes_dict.get(1082)

{'nome': 'Carla', 'curso': 'Engenharia'}

## O trabalho não desapareceu

::: {.prompt-gold}
Parte do trabalho foi transferida para a **estrutura** e para sua implementação.
:::

<div class="fragment small-note">Hoje não precisamos explicar como o dicionário realiza isso internamente.</div>

::: {.fragment .question-big}
Então o dicionário “ganhou”?
:::

## Mudamos a operação

### Agora queremos todos os estudantes de Ciência de Dados

```python
def estudantes_do_curso(estudantes, curso):
    encontrados = []
    for matricula, estudante in estudantes.items():
        if estudante["curso"] == curso:
            encontrados.append((matricula, estudante))
    return encontrados
```

::: {.fragment .prompt-gold}
Onde reapareceu o percurso?
:::

In [11]:
def estudantes_do_curso(estudantes,curso):
    encontrados=[]
    for matricula, estudante in estudantes.items():
        if estudante["curso"] == curso:
            encontrados.append((matricula, estudante))
    return encontrados
estudantes_do_curso(estudantes_dict,"CD")

[(1023, {'nome': 'Ana', 'curso': 'CD'}),
 (1047, {'nome': 'Bruno', 'curso': 'CD'}),
 (1125, {'nome': 'Daniel', 'curso': 'CD'})]

## <span class="gold">Mais rápido para qual operação?</span> {.question-slide}

<div class="fragment small-note">Uma representação pode favorecer uma operação sem favorecer todas.</div>

## E se organizássemos os dados de outra maneira?

```text
              1082
             /    \
          1047    1201
          /       /  \
       1023    1125  1350
```

::: {.fragment .question-big}
Para procurar 1125, precisamos examinar todos os estudantes?
:::

<div class="fragment prompt-gold">1082 → 1201 → 1125</div>

In [12]:
class No:
    def __init__(self, matricula, estudante):
        self.matricula=matricula; self.estudante=estudante; self.esquerda=None; self.direita=None

def inserir(no, matricula, estudante):
    if no is None: return No(matricula, estudante)
    if matricula < no.matricula: no.esquerda=inserir(no.esquerda, matricula, estudante)
    else: no.direita=inserir(no.direita, matricula, estudante)
    return no

raiz=None
for matricula,nome in [(1082,"Carla"),(1047,"Bruno"),(1201,"Eva"),(1023,"Ana"),(1125,"Daniel"),(1350,"Fábio")]:
    raiz=inserir(raiz, matricula, {"nome":nome})

## Podemos entender uma árvore sem saber implementá-la?

```python
def buscar_arvore(no, matricula):
    if no is None:
        return None
    if matricula == no.matricula:
        return no.estudante
    if matricula < no.matricula:
        return buscar_arvore(no.esquerda, matricula)
    return buscar_arvore(no.direita, matricula)
```

::: {.fragment .prompt-gold}
**Você não precisa saber produzir esse código hoje.** Consegue entender a estratégia?
:::

In [13]:
def buscar_arvore_com_caminho(no, matricula, caminho=None):
    if caminho is None: caminho=[]
    if no is None: return None, caminho
    caminho=caminho+[no.matricula]
    if matricula == no.matricula: return no.estudante, caminho
    if matricula < no.matricula: return buscar_arvore_com_caminho(no.esquerda, matricula, caminho)
    return buscar_arvore_com_caminho(no.direita, matricula, caminho)
resultado,caminho=buscar_arvore_com_caminho(raiz,1125)
print("caminho:"," → ".join(map(str,caminho)))
print("resultado:",resultado)

caminho: 1082 → 1201 → 1125
resultado: {'nome': 'Daniel'}


## O código revela a representação

:::: {.columns}
::: {.column width="32%"}
### Lista
```python
for estudante in estudantes:
    ...
```
**Percorrer**
:::
::: {.column width="32%"}
### Dicionário
```python
estudantes.get(matricula)
```
**Acessar por chave**
:::
::: {.column width="32%"}
### Árvore
```python
if alvo < no.matricula:
    buscar(no.esquerda)
```
**Decidir onde continuar**
:::
::::

::: {.fragment .prompt-gold}
A diferença não está apenas na sintaxe.
:::

## E se os dados estiverem ordenados?

```python
matriculas = [1023, 1047, 1082, 1125, 1201, 1350]
```

::: {.fragment .question-big}
A ordenação nos permite fazer algo que não podíamos fazer antes?
:::

In [14]:
from bisect import bisect_left
matriculas=[1023,1047,1082,1125,1201,1350]
alvo=1125
posicao=bisect_left(matriculas,alvo)
encontrado=posicao < len(matriculas) and matriculas[posicao] == alvo
print("posição:",posicao)
print("encontrado:",encontrado)

posição: 3
encontrado: True


## Quatro comportamentos que já conseguimos reconhecer

<div class="question-list">
  <div class="fragment"><strong>Lista:</strong> percorre elementos.</div>
  <div class="fragment"><strong>Dicionário:</strong> acessa pela chave.</div>
  <div class="fragment"><strong>Árvore:</strong> decide em qual direção continuar.</div>
  <div class="fragment"><strong>Dados ordenados:</strong> permitem estratégias que aproveitam a ordem.</div>
</div>

::: {.fragment .prompt-gold}
Ainda não calculamos formalmente os custos. Mas já conseguimos **descrever o trabalho**.
:::

## AGORA É COM VOCÊ {.question-slide}

::: {.prompt-gold}
### Notebook Estudante — Atividade 2
Sem calcular formalmente a complexidade, descreva o trabalho que cada código parece realizar.
:::

- percorre elementos?
- acessa por uma chave?
- descarta possibilidades?
- depende de uma organização prévia?

<div class="small-note">Primeiro faça uma previsão. Depois execute e interprete.</div>

## Prever → executar → interpretar

<div class="three-words"><span>PREVISÃO</span><span class="blue">EXECUÇÃO</span><span class="gold">INTERPRETAÇÃO</span></div>

<div class="question-list">
  <div class="fragment">Sua previsão se confirmou?</div>
  <div class="fragment">O que o código fez de fato?</div>
  <div class="fragment gold-text">Que característica da representação tornou isso possível?</div>
</div>

## Agora podemos caracterizar o problema

<div class="prompt-gold" style="font-size: 0.88em; line-height: 1.35;">

**Problema → Dados → Operações → Representação**

**Trabalho esperado → Volume → Restrições**

</div>

<div class="fragment small-note">
A ficha surge depois da investigação — não antes dela.
</div>


## O que significa “trabalho esperado”?

<div class="question-list">
  <div class="fragment">olhar <strong>um</strong> elemento?</div>
  <div class="fragment">olhar <strong>vários</strong>?</div>
  <div class="fragment">talvez <strong>todos</strong>?</div>
  <div class="fragment">comparar?</div>
  <div class="fragment">percorrer?</div>
  <div class="fragment">reorganizar?</div>
</div>

::: {.fragment .prompt-gold}
E se forem 10 registros? E se forem 10 milhões?
:::

## Um requisito do Sistema Acadêmico

> Consultas por **matrícula** são muito frequentes.  
> Também precisamos listar estudantes por **curso**.  
> Novos estudantes são inseridos regularmente.

::: {.fragment .prompt-gold}
Caracterize: **Problema · Dados · Operações · Representação · Trabalho esperado · Volume · Restrições**
:::

## Escolhas computacionais têm consequências

<div class="question-list">
  <div class="fragment">facilitar uma operação ↔ dificultar outra;</div>
  <div class="fragment">simplicidade ↔ desempenho;</div>
  <div class="fragment">clareza ↔ compactação.</div>
</div>

::: {.fragment .question-big}
Existe uma escolha sem trade-offs?
:::

## AGORA É COM VOCÊ {.question-slide}

::: {.prompt-gold}
### Notebook Estudante — Atividade 3
Escolha uma representação para o requisito apresentado e **justifique**.
:::

A justificativa deve mencionar:

**dados + operação predominante + consequência da escolha**

<div class="small-note">Se o tempo estiver curto, esta atividade pode ser feita oralmente.</div>

## Voltando à pergunta inicial

### Existe uma única forma correta de representar os dados?

<div class="fragment prompt-gold"><strong>Não avaliamos uma representação isoladamente.</strong></div>

<div class="fragment small-note">Avaliamos em relação ao problema, aos dados, às operações, ao volume e às restrições.</div>

## Uma expressão apareceu várias vezes

<div class="prompt-gold" style="font-size: 0.95em; margin-top: 1.2em;">

**“Parece exigir menos trabalho...”**

</div>

<div class="fragment" style="font-size: 1.35em; text-align: center; margin-top: 1.4em;">

Mas **“parece”** é suficiente?

</div>


## A próxima investigação {.question-slide}

### Como podemos comparar **sistematicamente** o trabalho necessário para realizar diferentes operações quando o volume de dados cresce?

<div class="fragment small-note">**Semana 03 — Operações fundamentais sobre conjuntos de dados e experimentação inicial**</div>